#!/usr/bin/env php

<?php

require  __DIR__ . '/vendor/autoload.php';
require(__DIR__ . '/helpers/helpers.php');

$dotenv = Dotenv\Dotenv::create(__DIR__);
$dotenv->load();

define('YII_DEBUG', true);

require  __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
